### ISSUE TITLE
Need help with initial setup.

### ISSUE THREAD

**Issue by mano1979** [henriksod/Fabrik2DArduino#10]
I am building a robot at the moment and started to work on walk movements. the robot I am building is this one: https://www.thingiverse.com/thing:3445283

I need to set up your library for my specific ">" shaped leg.

What i'm trying to do is make the leg do a step. So first when the leg is on the ground, it needs to pull up his leg, then move the leg forward and then put his foot down, and then slowly move the paw to the back. This is a video I made : https://twitter.com/i/status/1144728343885045761

the issue I had was, when the leg moves to the back, the foot moves in a arc instead of straight, that is why I want to use your library. Also your lib will make all other code easier.

I am using MG-996 servos which by default turn the other way. so 180 degrees is 0 and vice versa.

hope you can help me with a initial setup/ example

**Comment by mano1979** [comment]
Anyone? I'm really stuck here....

**Comment by mano1979** [comment]
This is how I made the servos move in the video:

![servodirection](https://user-images.githubusercontent.com/16356475/60517159-78cf4380-9cdf-11e9-8526-47bc4d1a7c6e.png)

**Comment by mano1979** [comment]
With the 2dof examlle code (and adjusting some things) i got movement in one direction (Z) . The tip of the leg is moving up and down with both motors moving.

I am not sure is this is how it should move.
Also this i supposedly movement on the Y axis according to the example. How would i make a movement on the X axis?
![Screenshot_20190703-225019_Samsung Notes](https://user-images.githubusercontent.com/16356475/60624232-0ba5d600-9de5-11e9-8475-9a7207b5bd32.jpg)

**Comment by henriksod** [comment]
Sorry for the late reply,

unfortunately, it is pretty hard to come up with a code that works for your case without the actual hardware to test on. This should not be hard at all to do if you can construct a testbed though. The library expects the arm to be pointing straight when the servo angles are zero. The library works in the unit circle, though. So if the library outputs the angle 0 for a given servo, you should, in fact, add it by 90 degrees in order for it to be correct. Since you want to have the arm point down instead of up, you can simply invert the x and y coordinates when sending them into the library. Then you can select the desired coordinates like normal, with the first joint as the reference point (0,0).

The coordinate system that you drew is the coordinate system of the end effector. I would advise you to use the coordinate system of the arm instead, which is located at the first joint.

**Comment by mano1979** [comment]
![Screenshot_20190804-190501_Email](https://user-images.githubusercontent.com/16356475/62426883-02ad6a80-b6eb-11e9-8ebb-ffdd7f53efc7.jpg)
Thank you for your reply. What do you mean with "the library works in a circle"?

And the 2nd point: how would i move the foot if the coordinate systen is at the first joint? (Might be a stupid question but i have no experience with this).
How i understand this is that instead of moving the foot i should move the entire body and leave the foot where it is?

**Comment by kbickham** [comment]
I'm testing a 2d arm with sensors not, about to use this with a modified unistep 2 library. You're going to have to do some math on the translations depending on where your first motor mounts I'm guessing. Man, I just screwed my mounts to a wood frame and put a wood platform beneathr it. Go 3d print your arms / motor mount with a low infill so it's cheap, so you can test.

**Comment by henriksod** [comment]
> Thank you for your reply. What do you mean with "the library works in a circle"?

It was a bad choice of words to explain this. The unit circle has it's 0 degree position in the same direction as the unit vector (1,0). You want to place the servo so that 0 degrees for the servo is 90 degrees off from 0 degrees of the library (0 degrees for the servo is along the y axis while 0 degrees for the library is along the x axis). I think this will be different for your case though... You should probably place the servo differently and thus the offset will be different. It's all relative, that is why I am overcomplicating my answer. Sorry about that. I have not tried the case you are describing myself so I have no idea what configuration you need for it to work. I do know that it will work if done correctly, though.

> And the 2nd point: how would i move the foot if the coordinate systen is at the first joint? (Might be a stupid question but i have no experience with this).

You should have a pressure sensor at the foot to know if you are touching the ground or not. Otherwise, you still know the length of your "leg" so it is easily transformable using forward kinematics. This whole library builds upon moving the "foot" or "hand" or as it is called in more scientific terms, the "end effector". The x- and y coordinate you send in to determine the position of the end effector, not the first joint. But (!!) the 0th coordinate system is located at the first joint. See each joint as being associated with its own coordinate system. Kinematics is all about transforming between different coordinate systems to find relations between axes in terms of position and orientation.

> How i understand this is that instead of moving the foot i should move the entire body and leave the foot where it is?

No, you are still moving the foot. Look at the illustrations in the repo.

**Comment by kbickham** [comment]
So I'm implementing my model. My only question is if you have an existing way to implement constraints. Basically to avoid hitting the wall, I have that I need to keep 0<angle 1<95(ish), and of course for angle  2... it depends on the the first. I have though at least derived that Length1*cos(angle1) + Length2*cos(angle2) need be <= 180mm and  Length1*sin(angle1) + Length2*sin(angle2)need be <210mm. I see you have a function that effect the approach angle, most likely this will be the best existing solution ? Not to thread jack, I don't want to start a duplicate topic. Either way, thanks for making this library!
![design](https://user-images.githubusercontent.com/24517278/62645990-f572c480-b912-11e9-98db-c2aa8795cf42.jpg)

**Comment by mano1979** [comment]
> I'm testing a 2d arm with sensors now, about to use this with a modified unistep 2 library. You're going to have to do some math on the translations depending on where your first motor mounts I'm guessing. Man, I just screwed my mounts to a wood frame and put a wood platform beneathr it. Go 3d print your arms / motor mount with a low infill so it's cheap, so you can test.

I actually allready have most of my robot printed.
![20190709_123907](https://user-images.githubusercontent.com/16356475/62666064-23dbb880-b982-11e9-9b75-0cc1a886f8f4.jpg)

**Comment by henriksod** [comment]
Sorry for not being able to answer this in such a long time. Legged robots is an unexplored topic for me. I am certain that the library can handle this use case. I will make a video in the near future explaining exactly how to use this library and maybe you will get some clarifications. This is a really cool project you are working on. I hope you managed to solve some of the problems you had!
