### ISSUE TITLE
data range problem

### ISSUE THREAD

**Issue by Wangs121** [henriksod/Fabrik2DArduino#11]
in `fabrik2D.solve(x,y,lengths);`, x should be greater than 0. I tried so many times and thought this library can not work, finally measure the result in `SolidWorks` and find out the problem. 
Besides, the row `result = fabrik2D.getAngle(n)* 57296 / 1000;` , if `result` is less than 0, `result+=180`, then you can get the current `result` which clockwise is positive.

**Comment by Wangs121** [comment]
I think these tips deserve add to `readme.md`

**Comment by henriksod** [comment]
Regarding your first point, I totally agree. I will add a safety measure in the code so that the IK returns fail to compute if you input x <= 0. The thing is that the library can compute when x<=0, but the angles output from the library may look strange since the robot is trying to reach behind it.

Regarding your second point, I do not agree. The angles output from the library **are meant to become negative** because the zero angle is along the y-axis. You should put the servos pointing along the y-axis when they are set at 90 degrees. Then you use the angles from the library in the following way, which I have already written in the Usage example:

```
shoulder.write(min(180, max(0, shoulderAngle + 180/2)));
elbow.write(min(180, max(0, elbowAngle + 180/2)));
```

**Comment by Wangs121** [comment]
thank u for your generous reply, These rules I wrote only works for my biped robot,I should consider more in other situation. Good luck in everything!
