### ISSUE TITLE
Schematics

### ISSUE THREAD

**Issue by jendib** [henriksod/Fabrik2DArduino#7]
Hello, great project!

However I cannot make it work for a simple robot arm exactly like the one here:
https://raw.githubusercontent.com/henriksod/Fabrik2DArduino/master/setup/4DOFSetup.png

I'm getting negative angle, which is making the arm pointing backward.

Are you sure the angle are in the right direction?

Also the 4DOF code example doesn't match this schematic right? I'm very confused on how to read the schematics and the code examples.

Thanks!

**Comment by henriksod** [comment]
I will have to create an example robotic arm for this. Unfortunately, I do not have any access to the hardware at the moment. The example should be as the schematic. Sure, it is a bit strange that the z-axis is not pointing upward, but it made more sense implementing it this way since you are only able to move in the z-axis by rotating the base of the robotic arm.

Have you tried negating the angle?

I will look into this in the next coming weeks.

**Comment by jendib** [comment]
Yes I tried every transformating I could to try to have a proper movement, but I couldn't get to make it work.
Also I don't understand why the 4DOF example has 3 measurements, but the on the schematic I can only see an arm+a forearm, so 2 measurements.

**Comment by henriksod** [comment]
The configuration examples are only to illustrate how you should orient the servos. They are not schematics of how you should have your robotic arm look. The 3D configuration is not the same as the 4D example since one joint is missing. This is because it is easier to present the concept without any unnecessary clutter.

**Comment by jendib** [comment]
But is it possible to solve in 3D with only 2 joints + the rotation base?
The documentation on the solve2 method is saying otherwise:
https://github.com/henriksod/Fabrik2DArduino/blob/51b4d6ae3f01e3357a880921f2f0bc5affcd4c50/src/FABRIK2D.cpp#L319

**Comment by henriksod** [comment]
No it is not possible. I can redraw the illustrations. It would not take much time. But I wanted to keep it simple enough so that the images would be easy to understand.

**Comment by henriksod** [comment]
I have now updated the configurations. I noticed that I had mixed conceptions about the joint angle and servo angle. The joint angle (library angle) should be zero whereas the servo angle should be 90 degrees when the arm is pointing straight up. Sorry for the inconvenience, I hope everything is much more clear now.
